name: AirDrop
main: source\airdrop\Loader
version: 1.0.0
api: 5.15.0
author: Joshet18
permissions:
  airdrop.command:
    description: "Permiso generico"
    default: op
  airdrop.edit.command:
    description: "Permiso generico"
    default: op
  airdrop.give.command:
    description: "Permiso generico"
    default: op
commands:
  airdrop:
    description: "Airdrop command"
    permission: "airdrop.command"
    usage: "/airdrop <action>"